export const BULLET_GENERATOR_PROMPT_TEMPLATE = `
SUMMARIZE THE BELOW PRIVACY POLICY STATEMENT TEXT AND EXTRACT CRITICAL INFORMATION.
AND CREATE A LIST OF BULLET POINTS FOR THE SAME. DO NOT EXCEED MORE THAN 20 BULLET POINTS.
LIST THEM IN A SEQUENTIAL ORDER AND SEPARATE THEM BY A NEW LINE.
ONLY DISPLAY THE BULLET POINTS AND NOT THE SUMMARY.
DO NOT CREATE ANY SUB SECTIONS. JUST KEEP IT AS A LIST. NO HEADINGS.

PRIVACY POLICY STATEMENT TEXT:
{input}
`;
